### ISSUE TITLE
Issue with trying to run program with ESPN & Sleeper

### ISSUE THREAD

**Issue by stsmith313** [mikemountain/fantasy-football-scoreboard#42]
<img width="903" alt="Capture" src="https://user-images.githubusercontent.com/25472602/235488323-9e7c655c-63e1-4b56-9021-e98fc15c7788.PNG">
When I'm trying to run the program I am getting an error:

Traceback (most recent call last):
  File "/home/sam/fantasy-football-scoreboard/main.py", line 38, in <module>
    data = Data(config)
  File "/home/sam/fantasy-football-scoreboard/data/data.py", line 23, in __init__
    self.api = self.choose_api()
  File "/home/sam/fantasy-football-scoreboard/data/data.py", line 38, in choose_api
    return espn.ESPNFantasyInfo(self.config.espn_league_id, self.config.espn_team_id, self.config.espn_swid, self.config.espn_s2, self.week, self.config.season)
  File "/home/sam/fantasy-football-scoreboard/data/espn_api_parser.py", line 19, in __init__
    self.teams_info = self.get_teams()
  File "/home/sam/fantasy-football-scoreboard/data/espn_api_parser.py", line 114, in get_teams
    owner = user['primaryOwner']
KeyError: 'primaryOwner'

**Comment by stsmith313** [comment]
Nevermind I got it working.

**Comment by Mdawson25** [comment]
How did you correct this, I am having the same issue.

**Comment by stsmith313** [comment]
> How did you correct this, I am having the same issue.
> 
> ![code](https://user-images.githubusercontent.com/84669021/260144354-d258ab20-2fc1-4478-894c-639e645f8160.JPG)

Check the pull request I put in and update the code with it. That’s the code that is working for me right now.
